# GitLab CI configuration
#
# Requirements
#  - schmunk42/gitlab-runner >=4.2.0-rc1

before_script:
  - export BUILD_PREFIX=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}
  - export APP_MIGRATION_LOOKUP=@root/tests/codeception/_migrations
  - mkdir -p /tmp/${BUILD_PREFIX}

stages:
  - build
  - test_pre
  - test
  - report
  - cleanup
  - deploy

build:
  stage: build
  script:
      - cp .env-dist .env
      - make build

test:
  stage: test
  script:
      - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}${CI_BUILD_NAME}
      - set +e
      - bash build/scripts/${CI_BUILD_NAME}.sh || EXIT_CODE=$?
      - set -e
      - cp -r tests/codeception/_output/ /tmp/${BUILD_PREFIX}/${CI_BUILD_NAME}
      - exit ${EXIT_CODE}

test-allow_failure:
  stage: test_pre
  script:
      - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}${CI_BUILD_NAME}
      - set +e
      - bash build/scripts/${CI_BUILD_NAME}.sh || EXIT_CODE=$?
      - set -e
      - cp -r tests/codeception/_output/ /tmp/${BUILD_PREFIX}/${CI_BUILD_NAME}
      - exit ${EXIT_CODE}
  allow_failure: true
  only:
      - develop
  except:
    - tags

lint:
  stage: test_pre
  script:
      - make diagnose
      - set +e
      - bash build/scripts/lint.sh
      - set -e
      - cp -r tests/_lint/ /tmp/${BUILD_PREFIX}/${CI_BUILD_NAME} || EXIT_CODE=$?
      - exit ${EXIT_CODE}
  allow_failure: true

report:
  stage: report
  script:
    - cp -r /tmp/${BUILD_PREFIX} $(basename $PWD)-${CI_BUILD_REF}
  artifacts:
    paths:
      - $(basename $PWD)-${CI_BUILD_REF}
  when: always

cleanup:
  stage: cleanup
  script:
    - make TEST clean
    - export COMPOSE_PROJECT_NAME="${BUILD_PREFIX}test"
    - make TEST clean
    - export COMPOSE_PROJECT_NAME="${BUILD_PREFIX}test-allow_failure"
    - make TEST clean
    - rm -rf /tmp/${BUILD_PREFIX}
  when: always

deploy:
  stage: deploy
  script:
    - bash build/scripts/deploy.sh
  only:
    - master
    - tags
