# Phundament 4 - Local development overrides

php:
  volumes:
    - .:/app
  environment:
    - YII_ENV=dev
    - YII_DEBUG=1

nginx:
  ports:
    - '41080:80'
  volumes:
    - .:/app

mariadb:
  ports:
    - '41306:3306'
